complete : main.nest.sass.css learn.nest.sass.css blogMain.nest.sass.css posts.nest.sass.css content.nest.sass.css 404css.nets.sass.css

main.nest.sass.css : main.sass
	sass main.sass ../css/main.nest.sass.css --sourcemap=none
learn.nest.sass.css : learn.sass
	sass learn.sass ../css/learn.nest.sass.css --sourcemap=none
blogMain.nest.sass.css : blogMain.sass
	sass blogMain.sass ../css/blogMain.nest.sass.css --sourcemap=none
posts.nest.sass.css : posts.sass
	sass posts.sass ../css/posts.nest.sass.css --sourcemap=none
content.nest.sass.css : content.sass
	sass content.sass ../css/content.nest.sass.css --sourcemap=none
404css.nets.sass.css : 404css.sass
	sass 404css.sass ../css/404css.nest.sass.css --sourcemap=none
