defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      stylesheet: "css/content.nest.sass.css"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

destination: moonwards.com
exclude:
  - archive
  - graphics
  - details-shim-master
  - blenderstuff
  - working
  - LICENSE.txt
  - README.md
  - TODO.txt
  - basetemplate.html
  - extractor.sh
  - sass
  - directoryStructure
  - makefile
  - forum
  - drafts
markdown: kramdown
url: "https://www.moonwards.com"
excerpt_separator: end-excerpt
collections:
 rss:
