defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      stylesheet: "css/content.css"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

destination: moonwards.com
exclude:
  - graphics
  - details-shim-master
  - downloads
  - working
  - LICENSE.txt
  - expandingDirectories.build
  - build.sh
  - cleanup.sh
  - movedFiles.tmp
  - README.md
  - TODO.txt
  - basetemplate.html
  - extractor.sh
  - sass
  - directoryStructure
  - makefile
  - forum
  - drafts
  - tools
  - favicons
markdown: kramdown
url: "https://www.moonwards.com"
excerpt_separator: end-excerpt
plugins:
  - jekyll-timeago
collections:
 rss:
