defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      stylesheet: "css/content.nest.sass.css"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

destination: docs
exclude:
  - archive
  - graphics
  - details-shim-master
  - blenderstuff
  - working
  - LICENSE.txt
  - README.md
  - TODO.txt
  - basetemplate.html
  - extractor.py
  - Gemfile
  - Gemfile.lock
  - engines.sh
markdown: kramdown
url: "https://www.moonwards.com"
excerpt_separator: end-excerpt
collections:
 rss:
